<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite ignored="6" hostname="PFTBLR-RMZ-021" failures="2" tests="13" name="com.qa.clearpc.search.Search_pageTest" time="246.578" errors="0" timestamp="29 Mar 2021 06:05:25 GMT" skipped="0">
  <testcase classname="com.qa.clearpc.search.Search_pageTest" name="performSearchWithinOrganisation" time="18.562"/>
  <testcase classname="com.qa.clearpc.search.Search_pageTest" name="validateAutosuggetionsForAdvancedSearch" time="10.647"/>
  <testcase classname="com.qa.clearpc.search.Search_pageTest" name="performSearchWithinOrganisation" time="18.478"/>
  <testcase classname="com.qa.clearpc.search.Search_pageTest" name="ValidateSearchTipsMessageIsDispalyed" time="11.103"/>
  <testcase classname="com.qa.clearpc.search.Search_pageTest" name="validateGridAssetView" time="15.859"/>
  <testcase classname="com.qa.clearpc.search.Search_pageTest" name="performSearchWithinOrganisation" time="17.052"/>
  <testcase classname="com.qa.clearpc.search.Search_pageTest" name="performSearchWithinOrganisation" time="18.866"/>
  <testcase classname="com.qa.clearpc.search.Search_pageTest" name="performSearchWithinOrganisation" time="22.106"/>
  <testcase classname="com.qa.clearpc.search.Search_pageTest" name="validateSearchForInvalidData" time="43.568"/>
  <testcase classname="com.qa.clearpc.search.Search_pageTest" name="validateListAssetView" time="16.278"/>
  <testcase classname="com.qa.clearpc.search.Search_pageTest" name="performSearchWithinOrganisation" time="18.559">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.qa.clearpc.search.Search_pageTest.performSearchWithinOrganisation(Search_pageTest.java:99)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1289)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- performSearchWithinOrganisation -->
  <testcase classname="com.qa.clearpc.search.Search_pageTest" name="performSearchWithinOrganisation" time="18.733">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.qa.clearpc.search.Search_pageTest.performSearchWithinOrganisation(Search_pageTest.java:99)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1289)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- performSearchWithinOrganisation -->
  <testcase classname="com.qa.clearpc.search.Search_pageTest" name="validateDetailedAssetView" time="16.767"/>
  <testcase classname="com.qa.clearpc.shareLink.ShareLinkTest" name="validateAssetShareNotificationForExternalUser">
    <skipped/>
  </testcase> <!-- validateAssetShareNotificationForExternalUser -->
  <testcase classname="com.qa.clearpc.shareLink.ShareLinkTest" name="validateAssetShareNotificationForInternalUser">
    <skipped/>
  </testcase> <!-- validateAssetShareNotificationForInternalUser -->
  <testcase classname="com.qa.clearpc.shareLink.ShareLinkTest" name="validateAssetSharePopUp">
    <skipped/>
  </testcase> <!-- validateAssetSharePopUp -->
  <testcase classname="com.qa.clearpc.shareLink.ShareLinkTest" name="verifyAssetShareLinkFunctionality">
    <skipped/>
  </testcase> <!-- verifyAssetShareLinkFunctionality -->
  <testcase classname="com.qa.clearpc.shareLink.ShareLinkTest" name="ValidateAssetShareFunctionality">
    <skipped/>
  </testcase> <!-- ValidateAssetShareFunctionality -->
  <testcase classname="com.qa.clearpc.Login.LoginPageTest" name="validateLogin">
    <skipped/>
  </testcase> <!-- validateLogin -->
</testsuite> <!-- com.qa.clearpc.search.Search_pageTest -->
